### ISSUE TITLE
Issues with Session State

### ISSUE THREAD

**Issue by oltipreka** [jrieke/streamlit-analytics#1]
Hi guys, 
First, congratulations for the great idea of creating an analytics tool for Streamlit. 

**I am having an issue when using Streamlit_analytics with a Login class for single user given as an argument within get_session_state** 

Is there any rule where to precisely include insert .start_tracking() and .stop_tracking()  within a Streamlit app?

**Comment by jrieke** [comment]
Hey @oltipreka, thx for trying it out! Oh yeah it could be that this causes problems because streamlit-analytics uses session state to track widget interactions (and getting session state twice with different parameters is problematic). Could you post a short code snippet of how you use session state so I can see how to accomodate it?

Btw this is a super early prototype so please keep reporting if sth doesn't work ;)

**Comment by jrieke** [comment]
You can use [Streamlit's official session state feature](https://docs.streamlit.io/library/api-reference/session-state) now, which shouldn't cause these problems. Closing.
